parameters:
- name: 'environmentName'
  default: ''
- name: 'azureSubscription'
  default: ''
- name: 'KeyVaultName'
  default: ''
- name: 'sql_servername'
  default: ''
- name: 'sql_database'
  default: ''
- name: 'sql_login'
  default: ''
- name: 'secrets_Filter'
  default: ''
- name: 'host'
  default: ''
- name: 'USER'
  default: ''
- name: 'PASSWORD'
  default: ''

  
jobs:
- deployment: ${{ replace(parameters.sql_database, '-', '_') }}_${{ parameters.environmentName }}_Deploy # Jobs cannot have hyphens, thus we must swap for an underscore here using replace function
  displayName: "Deploy Liquibase"
  environment: ${{ parameters.environmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
#        - task: AzureKeyVault@1
#           displayName: 'Grab SQL Login and Password from Key Vault'
#           inputs:
#             azureSubscription: ${{ parameters.azureSubscription }}
#             KeyVaultName: ${{ parameters.KeyVaultName }}
#             secretsFilter: ${{ parameters.secrets_Filter }} 
#             RunAsPreJob: true
            
        #Deploy Liquibase
        - task: Docker@2
          displayName: 'Docker build'
          inputs:
            containerRegistry: 'dockerhub'
            repository: 'anveshvemula/liqu'
            command: 'build'
            Dockerfile: '${AGENT_TOOLSDIRECTORY}/Dockerfile'
        - bash: |
            sudo docker run --rm -v changelog.xml:/liquibase/changelog.xml anveshvemula/liqu:$(Build.BuildId) --changeLogFile=/changelog.xml --url="jdbc:sqlserver://$(host);USER=$(USER);PASSWORD=$(PASSWORD);" update
        

# # Docker
# # Build a Docker image
# # https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - master

# resources:
# - repo: self

# variables:
#   tag: '$(Build.BuildId)'

# stages:
# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#     - task: Docker@2
#       inputs:
#         containerRegistry: 'dockerhub'
#         repository: 'anveshvemula/liqu'
#         command: 'build'
#         Dockerfile: '**/Dockerfile'
#     - bash: |
#         sudo docker run --rm -v changelog.xml:/liquibase/changelog.xml anveshvemula/liqu:$(Build.BuildId) --changeLogFile=/changelog.xml --url="jdbc:sqlserver://$(host);USER=$(USER);PASSWORD=$(PASSWORD);" update
        
