name: SQL Liquibase deployment

resources:
  repositories:
    - repository: 'liq' # Friendly name
      type: 'github' # Repo type
      name: 'https://github.com/vemulaanvesh/liquibase.git' # Repo path
      endpoint: 'vemulaanvesh' # Service Connection for GitHub Installation Token

trigger:  
  branches:
    include: 
    - master

variables:
  databaseName: dmp-sqldb-runway-configuration
  keyVaultSecret: 'AZURE-SQL-SERVER-PASSWORD'

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
    
stages:

# Pre-Deploy Stages
- stage: Build
  displayName: 'liquibase Build'
  jobs:
  - template: 'azure-pipelines.yml@liq'
    parameters:
      host: '${{ variables.host }}' # This is a Compile Time Variable, since it is used in the Job name, this variable must be compile time
      USER: '${{ variables.USER }}'
      PASSWORD: '${{ variables.PASSWORD }}'


- stage: liquibase
  displayName: 'liquibase'
  jobs:  
  - template: 'azure-pipelines-1.yml@liq'
    parameters:
      environmentName: 'build'
      azureSubscription: 'DataManagementPlatformNonProd'
      KeyVaultName: 'dmp-kv-runway-build-001'
      sql_servername: 'dmp-sql-runway-build-001.database.windows.net'
      sql_database: ${{ variables.databaseName }}
      sql_login: 'admin-sql-admin-build-001'
      secrets_Filter: ${{ variables.keyVaultSecret }}
      sql_dacpac_path: ${{ variables.dacpacpath }}
      
  - template: 'azure-pipelines-1.yml@liq'
    parameters:
      environmentName: 'dev'
      azureSubscription: 'DataManagementPlatformNonProd'
      KeyVaultName: 'dmp-kv-runway-dev-001'
      sql_servername: 'dmp-sql-runway-dev-001.database.windows.net'
      sql_database: ${{ variables.databaseName }}
      sql_login: 'admin-sql-admin-dev-001'
      secrets_Filter: ${{ variables.keyVaultSecret }}
      sql_dacpac_path: ${{ variables.dacpacpath }}
