name: SQL Liquibase deployment

trigger:  
  branches:
    include: 
    - master

resources:
- repo: self

variables:
  databaseName: dmp-sqldb-runway-configuration
  PASSWORD: 'AZURE-SQL-SERVER-PASSWORD'
  USER: 'ANVESH'
  host: ${{ parameters-host }}

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
    
stages:

- stage: build
  displayName: 'liquibase-build'
  jobs:  
  - template: 'azure-pipelines-liq.yml'
    parameters:
      environmentName: 'build'
      host: liqu.database.windows.net
      USER: '${{ variables.USER }}'
      PASSWORD: '${{ variables.PASSWORD }}'

- stage: Dev
  displayName: 'liquibase-Dev'
  dependsOn:
  - build
  jobs:
  - template: 'azure-pipelines-liq.yml'
    parameters:
      environmentName: 'dev'
      host: liqu.database.windows.net 
      USER: '${{ variables.USER }}'
      PASSWORD: '${{ variables.PASSWORD }}'
  condition: or(and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main')), and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))