parameters:
- name: 'environmentName'
  default: ''
- name: 'azureSubscription'
  default: ''
- name: 'KeyVaultName'
  default: ''
- name: 'sql_servername'
  default: ''
- name: 'sql_database'
  default: ''
- name: 'sql_login'
  default: ''
- name: 'secrets_Filter'
  default: ''
- name: 'host'
  default: ''
- name: 'USER'
  default: ''
- name: 'PASSWORD'
  default: ''


jobs:
- deployment: ${{ parameters.environmentName }}
  displayName: "Deploy Liquibase"
  environment: ${{ parameters.environmentName }}

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          #clean: true
#        - task: AzureKeyVault@1
#           displayName: 'Grab SQL Login and Password from Key Vault'
#           inputs:
#             azureSubscription: ${{ parameters.azureSubscription }}
#             KeyVaultName: ${{ parameters.KeyVaultName }}
#             secretsFilter: ${{ parameters.secrets_Filter }} 
#             RunAsPreJob: true
        #Deploy Liquibase
        - task: Docker@2
          displayName: 'Docker build'
          inputs:
            repository: 'anveshvemula/liqu'
            command: 'build'
            dockerfile: '**/Dockerfile'
        - bash: |
            sudo docker run --rm -v changelog.xml:/liquibase/changelog.xml anveshvemula/liqu:$(Build.BuildId) --changeLogFile=/changelog.xml --url="jdbc:sqlserver://"${{ parameters.host }}";USER=$(USER);PASSWORD=$(PASSWORD);" update