name: SQL Liquibase deployment

trigger:  
  branches:
    include: 
    - master

resources:
- repo: self

variables:
  databaseName: dmp-sqldb-runway-configuration
  PASSWORD: 'AZURE-SQL-SERVER-PASSWORD'
  host_build: 'liqu.database.windows.net'
  host_dev: 'liqu.dev.database.windows.net'

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
  
stages:

- stage: build
  displayName: 'liquibase-build'
  jobs:  
  - template: 'azure-pipelines-liq.yml'
    parameters:
      environmentName: 'build'
      host_build: ${{ variables.host_build }}
      USER: '${{ variables.USER }}'
      PASSWORD: '${{ variables.PASSWORD }}'

- stage: Dev
  displayName: 'liquibase-Dev'
  dependsOn:
  - build
  jobs:
  - template: 'azure-pipelines-liq.yml'
    parameters:
      environmentName: 'dev'
      host_dev: ${{ variables.host_dev }} 
      USER: '${{ variables.USER }}'
      PASSWORD: '${{ variables.PASSWORD }}'
  condition: or(and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main')), and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))